module.exports = {
    200 : 'Success',
    400 : 'Invalid Parameter',
    401 : 'Authentication Failed.',
    1000 : 'Some unexpected error occurred.',
    1001 : 'Invalid request params.',
    1002 : 'Invalid user token.',
    1003 : 'Mobile number already exists.',
    1004 : 'User Name already exists.',
    1005 : 'Email already exists.',
    1007 : 'Coupon code already used for this month.Please use this code next month.',
    1008 : 'Please enter a valid coupon code.',
    1009 : 'Please verify your mobile number from My Profile section to use this coupon code.',
    1010 : 'Offer already used, please use a new one.',
    1011 : 'Coupon code already used. Please enter a valid code.',
    1012 : 'Coupon code expired.',
    1013 : 'Use %s coupon code while buying chips through Net Banking',
    1014 : 'Bonus Not Applicable',
    1015 : 'Please enter valid signup code',
    1016 : 'Offer is Invalid',
    1017 : 'Offer has already been claimed',
    1018 : 'Maximum limit reached',
    1019 : 'New payment is required',
    1020 : 'Payment is pending',
    1021 : 'Insufficient balance in account',
    1022 : 'Offer id is missing',
    1023 : 'transaction bonus info not found',
    1024 : 'user bonus master detail not found',
    1025 : 'bonus code validation failure',
    1026 : 'offer name already exists',
    1027 : 'prefix already exists',
    1028 : 'Duplicate bonus code',
    1029 : 'Bonus code already pending for approval',
    1030  : 'Bonus code not exist' ,
    1031: 'Webengage grant api is Inactive',
    1032: 'Bonus is already grant for this journeyId'
}
